[package]
name = "blitz"
version = "0.1.0"
edition = "2021"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
description = "Native iced-wgpu based renderer for Dioxus"
license = "MIT/Apache-2.0"
repository = "https://github.com/jkelleyrtp/blitz"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
