[package]
name = "blitz"
version = "0.1.0"
edition = "2021"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
description = "Native iced-wgpu based renderer for Dioxus"
license = "MIT/Apache-2.0"
repository = "https://github.com/DioxusLabs/blitz"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus", rev = "741cbcbccc30cc3311bbc74ecd15817180675479" }
dioxus-native-core = { git = "https://github.com/DioxusLabs/dioxus", rev = "741cbcbccc30cc3311bbc74ecd15817180675479" }
dioxus-native-core-macro = { git = "https://github.com/DioxusLabs/dioxus", rev = "741cbcbccc30cc3311bbc74ecd15817180675479" }
taffy = "0.2.2"
tokio = { version = "1.17.0", features = ["full"] }
lightningcss = "1.0.0-alpha.39"
cssparser = "0.29.2"
vello = { git = "https://github.com/linebender/vello", rev = "9721d4a6acd9cc7b852fbbcc33ecab9fba06d433" }
wgpu = "0.15"
tao = { version = "0.15.8", features = ["serde"] }
raw-window-handle = "0.4.2"
anymap = "0.12.1"
futures-util = "0.3.21"
fxhash = "0.2"
serde_json = "1.0.82"
serde = { version = "1.0.138", features = ["derive"] }
keyboard-types = "0.6.2"
rustc-hash = "1.1.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
console_log = "0.2"
wasm-bindgen-futures = "0.4.33"
web-sys = "0.3.60"